logger :
  color :
    debug : "\x1b[33m"
    info : "\x1b[32m"
    warning : "\x1b[38;5;208m"
    error : "\x1b[31m"
    critical : "\x1b[31;1m"
    reset : "\x1b[0m"
  log-format : '%(asctime)s - %(levelname)s - %(message)s'
  date-format : '%Y-%m-%d %H:%M:%S'
